### PR TITLE
Implemented new GoogleSignIn and added support for spm

### PR DESCRIPTION
**Pull request by mamilov**
Associated Issue:
https://github.com/firebase/FirebaseUI-iOS/issues/951

### CODE REVIEW

**Comment by mamilov** [comment]
@googlebot I signed it!

**Comment by morganchen12** [comment]
Hey @mamilov, thanks for the contribution! I'm currently working on updates that will conflict with yours; would you like to pursue this PR or just wait for my changes?

**Comment by mamilov** [comment]
@morganchen12 I will keep using the forked version for now and wait for your changes.

**Comment by morganchen12** [comment]
@mamilov this fork should no longer be necessary with the latest release.

**Pull request closed without merging**
