### PR TITLE
Brazilian portuguese translation of Firebase UI

### PR DESCRIPTION
**Pull request by danielpassos**
pt-BR translation port from https://github.com/firebase/FirebaseUI-Android/pull/384

PS: Not 100% sure if I should commit the `FirebaseUI.xcodeproj/project.pbxproj` file

### CODE REVIEW

**Comment by morganchen12** [comment]
Thanks for doing this! I'm not qualified to fully review it, but you absolutely should commit the `pbxproj` file, since if you don't Xcode won't know that those files exist. The reason the diff is so big is because we usually run [`pod deintegrate`](https://rubygems.org/gems/cocoapods-deintegrate) before committing.

**Comment by danielpassos** [comment]
@morganchen12 That was the exactly that tip I was looking for. How include the (translated) files without include all pod things ;)

Updated. Thanks for the tip!

**Comment by morganchen12** [comment]
FYI @drishi94, @yramanchuk

**Comment by morganchen12** [comment]
Closing this as localizations have been added by the auth team and we don't have a process for accepting external localizations. Sorry!

**Pull request closed without merging**
