### PR TITLE
Conform TOS/PP view to safe area insets

### LINKED ISSUE #439: Sign In buttons doesn't constrain to Safe Area
I realized that the Sign In buttons are constrained to the superview rather than the Safe area. This causes it to look strange on the iPhone X. Is there a way to fix this? Thanks.

### PR DESCRIPTION
**Pull request by morganchen12**
Fixes #439

### CODE REVIEW

**Comment by morganchen12** [comment]
Don't merge, looks like this breaks iOS 8 builds.

**Comment by Yue-Wang-Google** [comment]
Looks good to me. Thanks!

**Comment by mikezing12** [comment]
icon-app-29x29 3x

**Comment by wittawats** [comment]
opportunity

**Comment by morganchen12** [comment]
Closing since the change is smaller than the merge conflict, will re-create this PR when we drop iOS 8.

**Pull request closed without merging**
