### PR TITLE
Remove TwitterAuthUI because its dependency TwitterKit is deprecated.

### PR DESCRIPTION
**Pull request by Yue-Wang-Google**
Users are encouraged to use OAuth login instead.

### CODE REVIEW

**Comment by Yue-Wang-Google** [comment]
DO_NOT_SUBMIT. 

We will deprecate TwitterAuth first in the next release. This PR will be useful after the next release is out.

**Comment by morganchen12** [comment]
Related: #616, #618, #402

**Comment by Yue-Wang-Google** [comment]
Twitter deprecation PR was just submitted to Firebase SDK. See https://github.com/firebase/firebase-ios-sdk/pull/2663 .  Reopen this PR.

**Comment by Yue-Wang-Google** [comment]
Please hold off review. I will need to implement Twitter auth using OAuth.

**Comment by Yue-Wang-Google** [comment]
Code is available for review.

**Comment by Yue-Wang-Google** [comment]
travis is drunk. It failed at the same place as #663 while the latter could always gets passed. As none of our UI tests work right now, I'll just submit this

**Pull request merged**
