### PR TITLE
Add gif example for dragging the plist file

### PR DESCRIPTION
**Pull request by dakeshi**
Create gif for dragging plist in the project to make better instructions in README.

### CODE REVIEW

**Comment by morganchen12** [comment]
👍 Thanks!

**Comment by richard4339** [comment]
You might want to look at this a little closer. Your merged change has the GIF in the readme pointing to @dakeshi 's fork, not the @firebase main repo raw version of the file.

``

when it should be

``

It's only a minor problem until the fork goes away.

**Comment by morganchen12** [comment]
Thanks for catching this, it should be fixed now.

**Comment by richard4339** [comment]
No problem

**Comment by dakeshi** [comment]
Thank you for your reviews. @morganchen12 , @richard4339

**Pull request merged**
